# Generated by Django 4.2.16 on 2024-11-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.zone'),
        ),
    ]
