# Generated by Django 4.2.16 on 2025-01-08 20:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='base.project')),
            ],
        ),
    ]
