# Generated by Django 4.2.16 on 2025-01-13 20:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_location_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
