# Generated by Django 4.2.16 on 2025-01-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project_location_delete_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
