# Generated by Django 4.2.16 on 2025-01-17 20:56

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_project_latitude_remove_project_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(-5.93012, 54.5973), null=True, srid=4326),
        ),
    ]
