# Generated by Django 4.2.16 on 2025-02-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_project_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='geometry',
            new_name='shape',
        ),
    ]
