# Generated by Django 4.2.16 on 2025-02-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_message_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='base.project'),
        ),
    ]
