# Generated by Django 4.2.16 on 2025-04-23 14:57

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-5.93012, 54.5973), srid=4326),
        ),
        migrations.AlterField(
            model_name='project',
            name='shape',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
