# Generated by Django 4.2.16 on 2025-04-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_project_location_alter_project_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.project'),
        ),
    ]
